project_id = "medcare"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[local_smtp]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:8443"
additional_redirect_urls = ["http://localhost:8443/**", "http://127.0.0.1:8443/**"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.rate_limit]
email_sent = 10
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
